### ISSUE TITLE
Notion import does not handle slug duplicates

### ISSUE THREAD

**Issue by fredm00n** [framer/plugins#78]
**Describe the bug**
Notion import failed due to duplicated slug

**To Reproduce**
Simply import a Notion DB that has duplicate entries.

**Suggestions to fix/improve**
- A better error display (it's currently breaking the modal)
- Add an auto-increment digit to all duplicates so it doesn't fail
- Tickbox to ignore duplicates during import?

**Screenshots**
![image](https://github.com/user-attachments/assets/5f313e52-d0ee-49aa-88bc-b654b801b8cf)

Many thanks
fred

**Comment by niekert** [comment]
Hello! Thank you for raising the issue about the error not being displayed correctly. We fixed that in a recent version now.


About slug duplicates: we feel like duplicate slugs in a database likely indicates that you are adding duplicates items, and that this should be fixed at the source (in Notion) rather than the Plugin suffixing items with the same slug for you, because that behavior is a little implicit and easy to miss with a large collection.

Hope that makes sense.
